name: Build dockers

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '15 1 * * *'

jobs:

  docker-build-and-test:
    runs-on: ubuntu-latest
    name: Validating docker ${{ matrix.docker-suffix }}
    timeout-minutes: 30
    strategy:
      matrix:
        docker-suffix:  ['.edge', '.preview', '.latest']
    steps:
      - name: install redis tools
        run: sudo apt-get update && sudo apt-get install -y redis-tools
      - uses: actions/checkout@v2
      - name: build the docker
        run: |
          docker build -f Dockerfile${{ matrix.docker-suffix }} -t redismod:github${{ matrix.docker-suffix }} .
      - name: light test that redis runs
        run: |
          docker run -d -p 6379:6379 redismod:github${{ matrix.docker-suffix }}
          redis-cli -p 6379 ping
          redis-cli -p 6379 set foo bar
          redis-cli -p 6379 get foo|grep bar
          redis-cli -p 6379 json.set jsonfoo '.' '{"hello": "world"}'
          redis-cli -p 6379 json.get jsonfoo|grep hello
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_REDISFAB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_REDISFAB_TOKEN }}
      - name: docker push
        if: github.ref == 'refs/heads/master'
        run: docker push redismod:${{matrix.docker-suffix}}
