name: Nightly publish to dockerhub

on:
  schedule:
    - cron:  '5 1 * * *'

jobs:

  docker-nightly-publish:
    runs-on: ubuntu-latest
    name: Updating dockers ${{ matrix.docker-suffix }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        docker-suffix:  ['edge', 'preview', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: build the docker
        run: |
          docker build -f Dockerfile.${{ matrix.docker-suffix }} -t redismod:${{ matrix.docker-suffix }} .
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_REDISFAB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_REDISFAB_TOKEN }}
      - name: docker push
        run: docker push redismod:${{matrix.docker-suffix}}
